### ISSUE TITLE
Change the method of infection

### ISSUE THREAD

**Issue by MeghanaThatikonda** [bfarahdel/bfarahdel#1]
Instead of the same cell in the multigrid, make neighboring cells with a radius of 1 transmit infection.

**Comment by bfarahdel** [comment]
https://mesa.readthedocs.io/en/stable/apis/space.html#mesa.space.MultiGrid.get_neighbors

get_neighbors

**Comment by bfarahdel** [comment]
Changed the method of infection to a neighbor within a radius of 1.
